### ISSUE TITLE
ERROR: 9

### ISSUE THREAD

**Issue by SuperVK** [iKlem/linux-screeps-server-manager#8]
when I do ./screepsserver install, this error pops up (ERROR: 9) it's after I type "Y" in the console. ./screepsserver install-deps returns checkmarks
![screenshot_3](https://user-images.githubusercontent.com/31625323/34740822-0000b562-f581-11e7-99cc-cbc87e6b74f9.png)

**Comment by iKlem** [comment]
I see the problem.
The thing is i've put the "Y" in uppercase because it's the default option. This is something I see a lot in installation on Linux but it can be misleading.
The other problem is I haven't added the Y or N (in uppercase) to the check as you can see here : https://github.com/iKlem/linux-screeps-server-manager/blob/master/screepsserver#L114
And the error I put there isn't very helpful, my bad :)
I'll update it in a few minutes but you can relaunch the command and use the "y" (no uppercase)
