### ISSUE TITLE
node is installed despite it saying it is missing

### ISSUE THREAD

**Issue by Domkeykong** [iKlem/linux-screeps-server-manager#9]
[https://imgur.com/a/Agg09](url)
I have it installed using nvm.
Maybe there is the issue.

**Comment by iKlem** [comment]
The isssue is my way of checking the "package" by using pacman (arch) or dpkg-query (debian based) and maybe it isn't the best way. Another thing is i've stopped developping this version and made a new one using nodejs instead since screeps IS using node to work. I redirect you to https://github.com/iKlem/node-screeps-server-manager 
If it answer your issue, i can or you can close this issue :)

**Comment by Domkeykong** [comment]
NOT working with [https://github.com/iKlem/node-screeps-server-manager](url)!
the processes are starting and stopping with code 1.
relocating the issue to [https://github.com/iKlem/node-screeps-server-manager](url)?

**Comment by iKlem** [comment]
You can do the new issue onto the other repo yes.
